name: ghostchat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.18
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  encrypt: ^5.0.3
  crypto: ^3.0.6
  cloud_firestore: 5.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.PNG"
